# ~~~~ WIN HELPER CONSTANTS ~~~~ #
GWL_STYLE = -16
GWLP_HWNDPARENT = -8
WS_CAPTION = 0x00C00000
WS_THICKFRAME = 0x00040000

# ~~~~ STATIC COLORS ~~~~ #
PINK = "#FFE3E1"
OTHERPINK = "#FA9494"
LIGHTYELLOW = "#e4dccf"
ORANGE = "#FFAA22"
NICEPURPLE = "#B1B2FF"
NICEBLUE = "#AAC4FF"
LAVENDER = "#D2DAFF"
LIGHTPURPLE = "#EEF1FF"
DARKBLUE = "#3e477c"
NAVYBLUE = "#27364d"
WHITE = "#FFFFFF"
BLACK = "#000000"
TRANSPARENTGREEN = "#0F0F0F"
BUTTON = "button"
LABEL = "label"
AVENIRNEXT = r"Fonts\AvenirNext-Regular.ttf"
SFPRO = r"Fonts\SF-Pro.ttf"
INTER = r"Fonts\Inter-Regular.ttf"
INTERBOLD = r"Fonts\Inter-Bold.ttf"
URBANIST = r"Fonts\Urbanist-Medium.ttf"
SOLWAY = r"Fonts\Solway-Medium.ttf"